import * as React from "react";

import {
  AlgalBloom,
  AnerobicFermentation,
  Aquifer,
  Biodynamic,
  Biome,
  Biomimicry,
  BirdFriendly,
  CleanWater,
  Collaboration,
  CommunityComposting,
  CommunityLocal,
  CommunitySeedBank,
  CoverCrop,
  CropRotation,
  DeforestationFree,
  DryFarming,
  EcologicalIntensification,
  EquityGender,
  EquityRacial,
  Equity,
  ErosionControl,
  FishFriendly,
  FoodSecurity,
  FoodWasteRecovery,
  HealthyPh,
  HerbicideFree,
  HydroRestauration,
  HydrologicalCycle,
  ImprovedWaterStorage,
  IncreasedSoilMoisture,
  IncreasedWaterConservation,
  IndigenousKnowledge,
  IrrigationDeficit,
  IrrigationGrip,
  KnowledgeSharing,
  MultigenerationalOwnedFarm,
  RecycledContent10,
  RecycledContent100,
  RecycledContent25,
  RecycledContent30,
  RecycledContent40,
  RecycledContent50,
  RecycledContent60,
  RecycledContent70,
  RecycledContent75,
  RecycledContent80,
  RecycledContent90,
  ReducedPlasticUse,
  RestoreCulturaleIdentity,
  Salinization,
  SoilFertility,
  SoilMicroorganism,
  SoilOrganicMatter,
  SolidarityEconomy,
  VeteranOwnedFarm,
  WaterCycle,
} from "./";

const icons = {
  AlgalBloom: AlgalBloom,
  AnerobicFermentation: AnerobicFermentation,
  Aquifer: Aquifer,
  Biodynamic: Biodynamic,
  Biome: Biome,
  Biomimicry: Biomimicry,
  BirdFriendly: BirdFriendly,
  CleanWater: CleanWater,
  Collaboration: Collaboration,
  CommunityComposting: CommunityComposting,
  CommunityLocal: CommunityLocal,
  CommunitySeedBank: CommunitySeedBank,
  CoverCrop: CoverCrop,
  CropRotation: CropRotation,
  DeforestationFree: DeforestationFree,
  DryFarming: DryFarming,
  EcologicalIntensification: EcologicalIntensification,
  EquityGender: EquityGender,
  EquityRacial: EquityRacial,
  Equity: Equity,
  ErosionControl: ErosionControl,
  FishFriendly: FishFriendly,
  FoodSecurity: FoodSecurity,
  FoodWasteRecovery: FoodWasteRecovery,
  HealthyPh: HealthyPh,
  HerbicideFree: HerbicideFree,
  HydroRestauration: HydroRestauration,
  HydrologicalCycle: HydrologicalCycle,
  ImprovedWaterStorage: ImprovedWaterStorage,
  IncreasedSoilMoisture: IncreasedSoilMoisture,
  IncreasedWaterConservation: IncreasedWaterConservation,
  IndigenousKnowledge: IndigenousKnowledge,
  IrrigationDeficit: IrrigationDeficit,
  IrrigationGrip: IrrigationGrip,
  KnowledgeSharing: KnowledgeSharing,
  MultigenerationalOwnedFarm: MultigenerationalOwnedFarm,
  RecycledContent10: RecycledContent10,
  RecycledContent100: RecycledContent100,
  RecycledContent25: RecycledContent25,
  RecycledContent30: RecycledContent30,
  RecycledContent40: RecycledContent40,
  RecycledContent50: RecycledContent50,
  RecycledContent60: RecycledContent60,
  RecycledContent70: RecycledContent70,
  RecycledContent75: RecycledContent75,
  RecycledContent80: RecycledContent80,
  RecycledContent90: RecycledContent90,
  ReducedPlasticUse: ReducedPlasticUse,
  RestoreCulturaleIdentity: RestoreCulturaleIdentity,
  Salinization: Salinization,
  SoilFertility: SoilFertility,
  SoilMicroorganism: SoilMicroorganism,
  SoilOrganicMatter: SoilOrganicMatter,
  SolidarityEconomy: SolidarityEconomy,
  VeteranOwnedFarm: VeteranOwnedFarm,
  WaterCycle: WaterCycle,
};

interface IconProps {
  name: string;
  color: string;
  [x: string]: any;
}
export default function Icon({ name, color, ...props }: IconProps) {
  //@ts-ignore
  const Iconz = icons[name];
  if (Iconz) return <Iconz color={color} props={props} />;
  return <div></div>
}
